
services:
  mysql:
    image: mysql:8
    container_name: mysql_foodapp_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: foodapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql

  restaurant_service:
    build:
      context: ./RestaurantServiceServer
    container_name: restaurant_service
    restart: always
    ports:
      - "3005:3005"
    depends_on:
      - mysql
      - redis

  user_service:
    build:
      context: ./UserServiceServer
    container_name: user_service
    restart: always
    ports:
      - "3015:3015"
    depends_on:
      - mysql
      - redis

  delivery_agent_service:
    build:
      context: ./DeliveryAgentServer
    container_name: delivery_agent_service
    restart: always
    ports:
      - "3010:3010"
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
