
services:
  mysql:
    image: mysql:8
    container_name: mysql_foodapp_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: foodapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql

  # Optional: Your Node.js backend
  # backend:
  #   build: .
  #   container_name: backend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mysql
  #     - redis
  #   environment:
  #     DB_HOST: mysql
  #     DB_USER: user
  #     DB_PASSWORD: password
  #     DB_NAME: foodapp
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379

volumes:
  mysql_data:
